services:
  rides-api:
    build:
      context: ./rides-api
      dockerfile: Dockerfile
    container_name: cabify-rides-api

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - cabify-net

  postgres:
    image: postgres:16
    container_name: cabify-postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - cabify_pgdata:/var/lib/postgresql/data

    networks:
      - cabify-net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s


networks:
  cabify-net:
    name: cabify-net


volumes:
  cabify_pgdata:
